[package]
name = "rhi"
version = "0.1.0"
edition = "2024"
authors = ["triesap npub1tr33s4tj2le2kk9yzhfphdtss26gyn8kv7savnnjhj794nqp333q8e7grr"]
rust-version = "1.88.0"
license = "AGPL-3.0"
description = "Rhizome Nostr data vending machine (NIP-90)"

[dependencies]
radroots-core = { path = "../crates/core", features = ["std", "serde", "typeshare"]  }
radroots-events = { path = "../crates/events", features = ["serde"] }
radroots-events-codec = { path = "../crates/events-codec", features = ["nostr"] }
radroots-identity = { path = "../crates/identity" }
radroots-nostr = { path = "../crates/nostr", features = ["client", "codec", "events", "http"] }
radroots-runtime = { path = "../crates/runtime", features = ["cli"] }
radroots-trade = { path = "../crates/trade" }

anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
jsonrpsee = { version = "0.26", features = ["server"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
tokio = { version = "1", features = ["full"] }
thiserror = { version = "1" }
tracing = { version = "0.1" }
uuid = { version = "1.16.0", features = ["v4"] }
