[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"
license = "AGPL-3.0"

[workspace.dependencies]
radroots-core = { path = "../../crates/crates/core" }
radroots-events = { path = "../../crates/crates/events" }
radroots-events-codec = { path = "../../crates/crates/events-codec" }
radroots-identity = { path = "../../crates/crates/identity" }
radroots-nostr = { path = "../../crates/crates/nostr" }
radroots-runtime = { path = "../../crates/crates/runtime" }
radroots-trade = { path = "../../crates/crates/trade" }

anyhow = { version = "1" }
clap = { version = "4" }
config = { version = "0.15" }
futures = { version = "0.3" }
nostr = { version = "0.43.0", features = ["nip04"] }
nostr-sdk = { version = "0.43.0" }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
tempfile = { version = "3.19.1" }
thiserror = { version = "1" }
tokio = { version = "1" }
tracing = { version = "0.1" }
uuid = { version = "1.16.0" }
