# rhizome Nostr data vending machine configuration

[metadata]
# The name shown on the profile
name = "rhi"

# A full display name that can include emojis or symbols
# display_name = ""

# A profile biography or description 
# about = ""

# URL of profile picture
# picture = ""

# URL of banner image
# banner = ""

# URL of website
# banner = ""

# Profile mapping to DNS-based internet identifier
# nip05 = ""

# Lightning address LNURL format
# lud06 = ""

# Lightning address internet identifiers format
# lud16 = ""

[config]
# Where to write logs/rotations.
logs_dir = "logs"

# Path to the keys profile JSON.
keys_path = "keys.json"

# Generate a new key profile if none is found.
generate_keys = true

# Optional NIP-89 application handler identifier.
identifier = ""

# Relays to connect to for publishing/subscribing.
relays = [
  "ws://127.0.0.1:8080"
]