[metadata]
name = "rhi"
# display_name = ""
# about = ""
# picture = ""
# banner = ""
# banner = ""
# nip05 = ""
# lud06 = ""
# lud16 = ""

[config]
logs_dir = "logs"
relays = [
  "ws://127.0.0.1:8080"
]

[config.subscriber.backoff]
base_ms = 500
max_ms = 30000
factor = 2
jitter_ms = 0
